export const CommonProblem = [
  {
    title: "Fever",
    value: "Fever",
  },
  {
    title: "Headaches",
    value: "Headaches",
  },
  {
    title: "Allergies",
    value: "Allergies",
  },
  {
    title: "Cold and Flu",
    value: "Cold and Flu",
  },
  {
    title: "Diarrhea",
    value: "Diarrhea",
  },
  {
    title: "Stomach Aches",
    value: "Stomach Aches",
  },
  {
    title: "Other Problem",
    value: "Other Problem",
  },
];

export const TestCategories = {
  HISTOPATHOLOGY: "Histopathology & Cytopathology",
  XRAY: "X-Ray (Digital)",
  OTHERS: "Others",
  ULTRASOUND: "Ultrasound Imaging",
  VACCINATION: "Vaccination",
  CARDIAC: "Cardiac Imaging",
  HAEMATOLOGY: "Haematology",
  IMMUNOLOGY: "Immunology/Serology",
  CANCER_MARKER: "Cancer Marker",
  BIOCHEMICAL: "Biochemical Exam",
  MICROBIOLOGY: "Microbiology",
  HEPATITIS: "Hepatitis Profile",
  URINE: "Urine",
  HORMONE: "Hormone Test",
  CARDIOLOGY: "Cardiology",
  STOOL: "Stool"
};

export const TestsList = [
  // HISTOPATHOLOGY & CYTOPATHOLOGY
  { id: 1, title: "Histopathology", price: 2500, category: TestCategories.HISTOPATHOLOGY },
  { id: 2, title: "FNAC", price: 2000, category: TestCategories.HISTOPATHOLOGY },
  { id: 3, title: "Pap's Smear for Cytology", price: 1800, category: TestCategories.HISTOPATHOLOGY },
  { id: 4, title: "Sputum for Malignant Cell", price: 1500, category: TestCategories.HISTOPATHOLOGY },
  { id: 5, title: "Discharge fluid for Malignant Cell", price: 1600, category: TestCategories.HISTOPATHOLOGY },
  { id: 6, title: "Ba-Swallow of Oesophagus", price: 3500, category: TestCategories.HISTOPATHOLOGY },
  { id: 7, title: "Ba-enema double contrast", price: 4000, category: TestCategories.HISTOPATHOLOGY },
  { id: 8, title: "Ba-Meal", price: 3000, category: TestCategories.HISTOPATHOLOGY },
  { id: 9, title: "Ba-follow Through", price: 3200, category: TestCategories.HISTOPATHOLOGY },
  { id: 10, title: "Oral Cholecystography (OCG)", price: 2800, category: TestCategories.HISTOPATHOLOGY },
  { id: 11, title: "IVU with post mict. film", price: 4500, category: TestCategories.HISTOPATHOLOGY },
  { id: 12, title: "Retrograde Cystourethrogram", price: 3800, category: TestCategories.HISTOPATHOLOGY },
  { id: 13, title: "OPG", price: 1200, category: TestCategories.HISTOPATHOLOGY },

  // X-RAY (DIGITAL)
  { id: 14, title: "Chest P/A View", price: 800, category: TestCategories.XRAY },
  { id: 15, title: "Rt Lat.", price: 900, category: TestCategories.XRAY },
  { id: 16, title: "Lt Lat.", price: 900, category: TestCategories.XRAY },
  { id: 17, title: "KUB", price: 1000, category: TestCategories.XRAY },
  { id: 18, title: "Plain X-Ray Abdomen", price: 1200, category: TestCategories.XRAY },
  { id: 19, title: "Skull B/V", price: 1500, category: TestCategories.XRAY },
  { id: 20, title: "P.N.S. (O.M View)", price: 1200, category: TestCategories.XRAY },
  { id: 21, title: "Cervical Spine B/V", price: 1800, category: TestCategories.XRAY },
  { id: 22, title: "Lumbo-Dorsal Spine B/V", price: 2000, category: TestCategories.XRAY },
  { id: 23, title: "Lumbo-Sacral Spine B/V", price: 2000, category: TestCategories.XRAY },
  { id: 24, title: "Ba-Meal of Stomach and Duodenum", price: 3500, category: TestCategories.XRAY },
  { id: 25, title: "Thoracic spine B/V", price: 1800, category: TestCategories.XRAY },

  // OTHERS
  { id: 26, title: "Tuberculin Test / MT", price: 500, category: TestCategories.OTHERS },
  { id: 27, title: "Semen Analysis", price: 800, category: TestCategories.OTHERS },
  { id: 28, title: "Hb Electrophoresis", price: 2500, category: TestCategories.OTHERS },
  { id: 29, title: "Protein Electrophoresis", price: 2800, category: TestCategories.OTHERS },
  { id: 30, title: "HbA1C", price: 1200, category: TestCategories.OTHERS },
  { id: 31, title: "HIV (1+2)", price: 1500, category: TestCategories.OTHERS },
  { id: 32, title: "Skin/Nail Scraping for Fungus", price: 600, category: TestCategories.OTHERS },
  { id: 33, title: "AFB", price: 400, category: TestCategories.OTHERS },

  // ULTRASOUND IMAGING
  { id: 34, title: "Whole Abdomen & Pelvic Organs", price: 2500, category: TestCategories.ULTRASOUND },
  { id: 35, title: "HBS / Upper Abdomen", price: 2000, category: TestCategories.ULTRASOUND },
  { id: 36, title: "Lower Abdomen / Uterus & Adnexa", price: 1800, category: TestCategories.ULTRASOUND },
  { id: 37, title: "Pregnancy Profile", price: 2200, category: TestCategories.ULTRASOUND },
  { id: 38, title: "KUB / Genito-Urinary Tract", price: 2000, category: TestCategories.ULTRASOUND },
  { id: 39, title: "KUB with Prostate & Residual Volume (PVR)", price: 2500, category: TestCategories.ULTRASOUND },
  { id: 40, title: "Thyroid", price: 1500, category: TestCategories.ULTRASOUND },
  { id: 41, title: "Brain", price: 3000, category: TestCategories.ULTRASOUND },
  { id: 42, title: "Breasts", price: 1800, category: TestCategories.ULTRASOUND },
  { id: 43, title: "Scrotum/Testes", price: 1600, category: TestCategories.ULTRASOUND },
  { id: 44, title: "Soft Tissue", price: 1200, category: TestCategories.ULTRASOUND },

  // VACCINATION
  { id: 45, title: "Hepatitis B Vaccine", price: 800, category: TestCategories.VACCINATION },
  { id: 46, title: "Hepatitis A Vaccine", price: 1200, category: TestCategories.VACCINATION },
  { id: 47, title: "Chickenpox", price: 2500, category: TestCategories.VACCINATION },
  { id: 48, title: "Typhoid", price: 600, category: TestCategories.VACCINATION },

  // CARDIAC IMAGING
  { id: 49, title: "E.C.G", price: 500, category: TestCategories.CARDIAC },
  { id: 50, title: "E.T.T-Stress E.C.G", price: 2500, category: TestCategories.CARDIAC },
  { id: 51, title: "ECHOCARDIOGRAM-2D & M-MODE", price: 3500, category: TestCategories.CARDIAC },
  { id: 52, title: "Video Endoscopy", price: 8000, category: TestCategories.CARDIAC },

  // HAEMATOLOGY
  { id: 53, title: "TC,DC,Hb%ESR", price: 400, category: TestCategories.HAEMATOLOGY },
  { id: 54, title: "MP", price: 300, category: TestCategories.HAEMATOLOGY },
  { id: 55, title: "CC Count", price: 250, category: TestCategories.HAEMATOLOGY },
  { id: 56, title: "LE Cell", price: 800, category: TestCategories.HAEMATOLOGY },
  { id: 57, title: "Platelet Count", price: 300, category: TestCategories.HAEMATOLOGY },
  { id: 58, title: "BT,CT", price: 400, category: TestCategories.HAEMATOLOGY },
  { id: 59, title: "Prothrombin Time", price: 600, category: TestCategories.HAEMATOLOGY },
  { id: 60, title: "APTT", price: 700, category: TestCategories.HAEMATOLOGY },
  { id: 61, title: "Reticulocyte Count", price: 500, category: TestCategories.HAEMATOLOGY },
  { id: 62, title: "HCT/PCV", price: 300, category: TestCategories.HAEMATOLOGY },
  { id: 63, title: "Blood Film", price: 400, category: TestCategories.HAEMATOLOGY },

  // IMMUNOLOGY/SEROLOGY
  { id: 64, title: "Widal Test", price: 400, category: TestCategories.IMMUNOLOGY },
  { id: 65, title: "ASO Titer", price: 600, category: TestCategories.IMMUNOLOGY },
  { id: 66, title: "Febrile Antigen", price: 800, category: TestCategories.IMMUNOLOGY },
  { id: 67, title: "RA Test", price: 500, category: TestCategories.IMMUNOLOGY },
  { id: 68, title: "Rose Waaler Test", price: 700, category: TestCategories.IMMUNOLOGY },
  { id: 69, title: "CRP", price: 800, category: TestCategories.IMMUNOLOGY },
  { id: 70, title: "VDRL/City Only", price: 500, category: TestCategories.IMMUNOLOGY },
  { id: 71, title: "C3", price: 1200, category: TestCategories.IMMUNOLOGY },
  { id: 72, title: "C4", price: 1200, category: TestCategories.IMMUNOLOGY },
  { id: 73, title: "TPHA", price: 800, category: TestCategories.IMMUNOLOGY },
  { id: 74, title: "IgG", price: 1500, category: TestCategories.IMMUNOLOGY },
  { id: 75, title: "IgM", price: 1500, category: TestCategories.IMMUNOLOGY },
  { id: 76, title: "IgA", price: 1500, category: TestCategories.IMMUNOLOGY },
  { id: 77, title: "IgE", price: 1800, category: TestCategories.IMMUNOLOGY },
  { id: 78, title: "ANA", price: 2500, category: TestCategories.IMMUNOLOGY },
  { id: 79, title: "H-pylori", price: 1200, category: TestCategories.IMMUNOLOGY },
  { id: 80, title: "Anti Ds DNA", price: 2000, category: TestCategories.IMMUNOLOGY },
  { id: 81, title: "Anti DNA", price: 1800, category: TestCategories.IMMUNOLOGY },
  { id: 82, title: "Blood Group & Rh Factor", price: 300, category: TestCategories.IMMUNOLOGY },
  { id: 83, title: "Rh Antibody Titre", price: 1200, category: TestCategories.IMMUNOLOGY },
  { id: 84, title: "Coomb's Test (Direct/Indirect)", price: 800, category: TestCategories.IMMUNOLOGY },
  { id: 85, title: "ICT Tuberculosis", price: 1500, category: TestCategories.IMMUNOLOGY },
  { id: 86, title: "ICT Filaria", price: 1200, category: TestCategories.IMMUNOLOGY },
  { id: 87, title: "ICT Kala-azar", price: 1500, category: TestCategories.IMMUNOLOGY },
  { id: 88, title: "ICT Malaria", price: 800, category: TestCategories.IMMUNOLOGY },
  { id: 89, title: "ELISA of TB IgA/IgG/IgM", price: 2500, category: TestCategories.IMMUNOLOGY },
  { id: 90, title: "Antisperm Antibody", price: 2200, category: TestCategories.IMMUNOLOGY },
  { id: 91, title: "Dengue ICT", price: 1200, category: TestCategories.IMMUNOLOGY },
  { id: 92, title: "Dengue ELISA", price: 2500, category: TestCategories.IMMUNOLOGY },
  { id: 93, title: "Dengue NS1 Ag", price: 1800, category: TestCategories.IMMUNOLOGY },

  // CANCER MARKER
  { id: 94, title: "CA-15-3", price: 2500, category: TestCategories.CANCER_MARKER },
  { id: 95, title: "Free PSA", price: 2200, category: TestCategories.CANCER_MARKER },
  { id: 96, title: "CA-19-9", price: 2500, category: TestCategories.CANCER_MARKER },
  { id: 97, title: "AFP", price: 2000, category: TestCategories.CANCER_MARKER },
  { id: 98, title: "CA-125", price: 2500, category: TestCategories.CANCER_MARKER },
  { id: 99, title: "CEA", price: 2200, category: TestCategories.CANCER_MARKER },
  { id: 100, title: "PSA", price: 2000, category: TestCategories.CANCER_MARKER },
  { id: 101, title: "BHCG", price: 1800, category: TestCategories.CANCER_MARKER },
  { id: 102, title: "Total hCG", price: 1500, category: TestCategories.CANCER_MARKER },

  // MICROBIOLOGY
  { id: 103, title: "Blood for C/S", price: 1200, category: TestCategories.MICROBIOLOGY },
  { id: 104, title: "Throat Swab for RE CS KLB", price: 800, category: TestCategories.MICROBIOLOGY },
  { id: 105, title: "Sputum R/E,C/S,AFB,(Gm Stain)", price: 1000, category: TestCategories.MICROBIOLOGY },
  { id: 106, title: "Vaginal Swab R/E C/S Gm Stain", price: 900, category: TestCategories.MICROBIOLOGY },
  { id: 107, title: "Wound Swab for C/S", price: 700, category: TestCategories.MICROBIOLOGY },
  { id: 108, title: "Umbilical Swab for C/S", price: 600, category: TestCategories.MICROBIOLOGY },
  { id: 109, title: "Conjunctival Swab for C/S", price: 700, category: TestCategories.MICROBIOLOGY },
  { id: 110, title: "Aural Swab for C/S", price: 600, category: TestCategories.MICROBIOLOGY },
  { id: 111, title: "Prostatic/Urethral Smear", price: 800, category: TestCategories.MICROBIOLOGY },
  { id: 112, title: "R/E G/C CS Gm Stain", price: 900, category: TestCategories.MICROBIOLOGY },
  { id: 113, title: "Pus for R/E,C/S,Gm Stain", price: 800, category: TestCategories.MICROBIOLOGY },

  // BIOCHEMICAL EXAM
  { id: 114, title: "Plasma Glucose", price: 200, category: TestCategories.BIOCHEMICAL },
  { id: 115, title: "+ FPG", price: 150, category: TestCategories.BIOCHEMICAL },
  { id: 116, title: "+ RPS", price: 150, category: TestCategories.BIOCHEMICAL },
  { id: 117, title: "+ RPPG", price: 200, category: TestCategories.BIOCHEMICAL },
  { id: 118, title: "+2hrs ABF/Lunch/Dinner/75g glucose", price: 300, category: TestCategories.BIOCHEMICAL },
  { id: 119, title: "Urea/BUN", price: 200, category: TestCategories.BIOCHEMICAL },
  { id: 120, title: "S.Creatinine", price: 250, category: TestCategories.BIOCHEMICAL },
  { id: 121, title: "S.Uric Acid", price: 250, category: TestCategories.BIOCHEMICAL },
  { id: 122, title: "S.Calcium", price: 300, category: TestCategories.BIOCHEMICAL },
  { id: 123, title: "Inorganic Phosphatase", price: 300, category: TestCategories.BIOCHEMICAL },
  { id: 124, title: "S.Total Protein", price: 300, category: TestCategories.BIOCHEMICAL },
  { id: 125, title: "Electrolytes", price: 800, category: TestCategories.BIOCHEMICAL },
  { id: 126, title: "Globulin", price: 250, category: TestCategories.BIOCHEMICAL },
  { id: 127, title: "Albumin", price: 300, category: TestCategories.BIOCHEMICAL },
  { id: 128, title: "S.Bilirubin (Total/Direct/Indirect)", price: 400, category: TestCategories.BIOCHEMICAL },
  { id: 129, title: "S.GOT", price: 250, category: TestCategories.BIOCHEMICAL },
  { id: 130, title: "AG Ratio", price: 200, category: TestCategories.BIOCHEMICAL },
  { id: 131, title: "S.GPT", price: 250, category: TestCategories.BIOCHEMICAL },
  { id: 132, title: "Alk. Phosphatase", price: 300, category: TestCategories.BIOCHEMICAL },
  { id: 133, title: "GST", price: 400, category: TestCategories.BIOCHEMICAL },
  { id: 134, title: "LDH", price: 500, category: TestCategories.BIOCHEMICAL },
  { id: 135, title: "Acid Phosphatase (Total/Prostatic)", price: 600, category: TestCategories.BIOCHEMICAL },
  { id: 136, title: "S.Amylase", price: 500, category: TestCategories.BIOCHEMICAL },
  { id: 137, title: "CRP", price: 800, category: TestCategories.BIOCHEMICAL },
  { id: 138, title: "Lipid Profile", price: 1200, category: TestCategories.BIOCHEMICAL },
  { id: 139, title: "Triglyceride", price: 300, category: TestCategories.BIOCHEMICAL },
  { id: 140, title: "Cholesterol", price: 250, category: TestCategories.BIOCHEMICAL },
  { id: 141, title: "LDL Cholesterol", price: 400, category: TestCategories.BIOCHEMICAL },
  { id: 142, title: "HDL Cholesterol", price: 400, category: TestCategories.BIOCHEMICAL },
  { id: 143, title: "S.Magnesium", price: 500, category: TestCategories.BIOCHEMICAL },
  { id: 144, title: "TIBC", price: 600, category: TestCategories.BIOCHEMICAL },
  { id: 145, title: "S.Iron", price: 500, category: TestCategories.BIOCHEMICAL },
  { id: 146, title: "Folic Acid", price: 1200, category: TestCategories.BIOCHEMICAL },
  { id: 147, title: "Ferritin", price: 1500, category: TestCategories.BIOCHEMICAL },
  { id: 148, title: "Vitamin B-12", price: 1800, category: TestCategories.BIOCHEMICAL },
  { id: 149, title: "Aldehyde test", price: 400, category: TestCategories.BIOCHEMICAL },
  { id: 150, title: "Vitamin D (25 OH)", price: 2500, category: TestCategories.BIOCHEMICAL },
  { id: 151, title: "Aldolase", price: 800, category: TestCategories.BIOCHEMICAL },
  { id: 152, title: "eGFR", price: 300, category: TestCategories.BIOCHEMICAL },

  // HEPATITIS PROFILE
  { id: 153, title: "HBs Ag ELISA/Sreening", price: 600, category: TestCategories.HEPATITIS },
  { id: 154, title: "Anti HBs Ab", price: 800, category: TestCategories.HEPATITIS },
  { id: 155, title: "Anti HBc IgG", price: 1000, category: TestCategories.HEPATITIS },
  { id: 156, title: "HBe Ag", price: 1200, category: TestCategories.HEPATITIS },
  { id: 157, title: "Anti HBc IgM", price: 1200, category: TestCategories.HEPATITIS },
  { id: 158, title: "Anti HEV", price: 1500, category: TestCategories.HEPATITIS },
  { id: 159, title: "Anti HEV-IgM", price: 1800, category: TestCategories.HEPATITIS },
  { id: 160, title: "Anti HAV-IgM", price: 1800, category: TestCategories.HEPATITIS },

  // HORMONE TEST
  { id: 161, title: "T3", price: 500, category: TestCategories.HORMONE },
  { id: 162, title: "T4", price: 500, category: TestCategories.HORMONE },
  { id: 163, title: "FT3", price: 800, category: TestCategories.HORMONE },
  { id: 164, title: "FT4", price: 800, category: TestCategories.HORMONE },
  { id: 165, title: "TSH", price: 600, category: TestCategories.HORMONE },
  { id: 166, title: "Prolactin", price: 1000, category: TestCategories.HORMONE },
  { id: 167, title: "Estradiol", price: 1200, category: TestCategories.HORMONE },
  { id: 168, title: "LH", price: 800, category: TestCategories.HORMONE },
  { id: 169, title: "Progesterone", price: 1200, category: TestCategories.HORMONE },
  { id: 170, title: "FSH", price: 800, category: TestCategories.HORMONE },
  { id: 171, title: "Testosterone", price: 1200, category: TestCategories.HORMONE },
  { id: 172, title: "Cortisol", price: 1500, category: TestCategories.HORMONE },
  { id: 173, title: "Growth Hormone", price: 2000, category: TestCategories.HORMONE },

  // URINE
  { id: 174, title: "R/E", price: 200, category: TestCategories.URINE },
  { id: 175, title: "C/S", price: 600, category: TestCategories.URINE },
  { id: 176, title: "Pregnancy Test", price: 300, category: TestCategories.URINE },
  { id: 177, title: "Bile Salts", price: 200, category: TestCategories.URINE },
  { id: 178, title: "Bile Pigment", price: 200, category: TestCategories.URINE },
  { id: 179, title: "Urobilinogen", price: 200, category: TestCategories.URINE },
  { id: 180, title: "24 Hrs.Total Protein/Calcium /Phosphate", price: 800, category: TestCategories.URINE },
  { id: 181, title: "Bence Jones Protein", price: 600, category: TestCategories.URINE },

  // CARDIOLOGY
  { id: 182, title: "CK-MB", price: 1200, category: TestCategories.CARDIOLOGY },
  { id: 183, title: "LDH", price: 500, category: TestCategories.CARDIOLOGY },
  { id: 184, title: "Troponin I", price: 2500, category: TestCategories.CARDIOLOGY },
  { id: 185, title: "CRK-MB", price: 1500, category: TestCategories.CARDIOLOGY },

  // STOOL
  { id: 186, title: "R/E", price: 200, category: TestCategories.STOOL },
  { id: 187, title: "C/S", price: 600, category: TestCategories.STOOL },
  { id: 188, title: "OBT", price: 300, category: TestCategories.STOOL },
  { id: 189, title: "Dva Count", price: 400, category: TestCategories.STOOL },
  { id: 190, title: "Reducing Substance", price: 300, category: TestCategories.STOOL }
];